name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v5.1.0
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Run Gradle
      run: gradle --warning-mode=all assembleDebug
    - name: Find file
      run: find build/outputs/apk
    - name: Upload APK
      uses: actions/upload-artifact@v6.0.0
      with:
        name: hisense.apk
        path: build/outputs/apk/debug/hisense-debug.apk
