name: Test

on: [workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Default Environment
      run: | 
        echo "BUILD_TYPE_MC=Debug" >>$GITHUB_ENV
        echo "BUILD_TYPE_LC=debug" >>$GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v6.0.2
    - name: Setup Java
      uses: actions/setup-java@v5.1.0
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Check available tools
      run: sdkmanager --list
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v3.2.1   
      with:
       log-accepted-android-sdk-licenses: false
       packages: tools
    - name: Test apksigner
      run: apksigner --help
