name: Test

on: [workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Default Environment
      run: | 
        echo "BUILD_TYPE_MC=Debug" >>$GITHUB_ENV
        echo "BUILD_TYPE_LC=debug" >>$GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v6.0.2
    - name: Setup Java
      uses: actions/setup-java@v5.1.0
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Checks
      run: env
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v4.0.1 
      with:
       log-accepted-android-sdk-licenses: false
       packages: tools
    - name: Setup PATH
      run: |
        echo "/usr/local/lib/android/sdk/build-tools/37.0.0" >> $GITHUB_PATH
    - name: Test
      run: echo "$PATH"; apksigner
